### ISSUE TITLE
number got banned from telegram in one run

### ISSUE THREAD

**Issue by chivarpilones** [IvanGlinkin/CCTV#18]
how to set delay?

**Comment by IvanGlinkin** [comment]
there is a file `./backend/general_settings.py`
you can find `timesleep` variable which is setting up the delay

**Comment by Caquita-beep** [comment]
Hello ser. It seems that when I run the script tg closes my sessions in all my devices. 

I get:  telethon.errors.rpcerrorlist.SessionRevokedError: The authorization has been invalidated, because of the user terminating all sessions (caused by GetLocatedRequest)

And it's over. Any suggestion?
btw, can't find anywhere the general_settings.py file.

**Comment by IvanGlinkin** [comment]
Hi guys.
The app has been updated. now the settings file is generating automatically once you launch the app. 
The settings file is on the root directory `config.yaml`
